[package]
name = "dbFaker"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
ratatui = "0.30.0"
serde_json = "1.0.145"
crossterm = "0.27"
fake = "4.0"