number:
  title: "数字"
  default: random
  min: 0
  max: 999999

string:
  title: "字符串"
  default: random
  pool_size: 10

date:
  title: "日期"
  default: current

timestamp:
  default: current
  title: "时间戳"


